name: events

on:
  workflow_dispatch:
#  schedule:
#    - cron: '*/5 * * * *'

env:
  NODE_VERSION: '16.17.0'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ env.NODE_VERSION }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ env.NODE_VERSION }}
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: npm ci
      - name: Filter events
        id: filter_events
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          GITHUB_BOT_TOKEN: ${{ secrets.BOT_PAT }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: npm run filter-github-events
        timeout-minutes: 5
#      - name: Add repos filtered to issue
#        uses: actions/github-script@v6
#        env:
#          REPOS: ${{ steps.filter_events.outputs.repos }}
#        with:
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#          script: |
#            const { REPOS } = process.env;
#            const script = require('${{ github.workspace }}/.github/github-scripts/comment-issue-on-filter-events.js');
#            await script({ github, context, repos: REPOS })

#      - name: Fork repo using bot account
#        uses: actions/github-script@v6
#        env:
#          REPOS: ${{ steps.filter_events.outputs.repos }}
#          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
#          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
#        with:
#          github-token: ${{ secrets.BOT_PAT }}
#          script: |
#            const { REPOS, SUPABASE_URL, SUPABASE_KEY } = process.env;
#            const supabase = require('@supabase/supabase-js').createClient(SUPABASE_URL, SUPABASE_KEY);
#            const script = require('${{ github.workspace }}/.github/github-scripts/fork-repo-using-bot-account.js');
#            await script({ github, repos: REPOS, supabase })
