name: events

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'

env:
  NODE_VERSION: '16.17.0'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ env.NODE_VERSION }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ env.NODE_VERSION }}
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: npm ci
      - name: Filter events
        id: filter_events
        env:
          TOKEN: ${{ secrets.PAT }}
        run: npm run filter-github-events
      - name: Add repos filtered to issue
        uses: actions/github-script@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOS: ${{ steps.filter_events.outputs.repos }}
        with:
          script: |
            const { REPOS } = process.env;
            const script = require('${{ github.workspace }}/comment-issue-on-filter-events.js');
            await script({ github, context, repos: REPOS })
