name: remove-unused-forked-repos

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

env:
  NODE_VERSION: '16.17.0'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ env.NODE_VERSION }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ env.NODE_VERSION }}
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: npm ci
      - name: Remove unused forked repos
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          GITHUB_BOT_TOKEN: ${{ secrets.BOT_PAT }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: npm run remove-unused-forked-repos
        timeout-minutes: 5
